
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Debug Node and npm versions
        run: |
          node --version
          npm --version
        
      - name: Build project
        run: npm run build
        
      - name: Debug HTML content
        run: |
          echo "Checking index.html content:"
          cat dist/index.html | head -n 30
        
      - name: Verify build output
        run: |
          echo "Checking build output directory contents:"
          ls -la dist/
          echo "Checking JS files:"
          find dist -name "*.js" | sort
          echo "File sizes:"
          du -h dist/assets/js/* | sort -h
          echo "First 10 lines of main JS file:"
          head -n 10 $(find dist/assets/js -name "*main*.js" | head -n 1)
        
      - name: Setup CNAME file and GitHub Pages config
        run: |
          # Copy the CNAME file from public directory
          cp public/CNAME dist/CNAME
          # Make CNAME file visible in output for debugging
          echo "CNAME content:"
          cat dist/CNAME
          # Disable Jekyll processing
          touch dist/.nojekyll
          # Ensure permissions are correct
          chmod -R 755 dist
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
