
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Debug Node and npm versions
        run: |
          node --version
          npm --version
        
      - name: Build project
        run: npm run build
        
      - name: Verify CNAME file
        run: |
          echo "Creating CNAME file directly in dist directory"
          echo "heynia.com" > dist/CNAME
          echo "CNAME content:"
          cat dist/CNAME
          
      - name: Setup GitHub Pages files
        run: |
          echo "Setting up GitHub Pages configuration..."
          # Ensure dist directory exists
          mkdir -p dist
          
          # Add .nojekyll file to disable Jekyll
          touch dist/.nojekyll
          echo "✅ .nojekyll file created"
          
          # Double check CNAME file presence and content
          if [ -f "dist/CNAME" ]; then
            echo "✅ CNAME file exists in dist/"
            echo "CNAME content:"
            cat dist/CNAME
          else
            echo "❌ CNAME file missing in dist/. Creating one..."
            echo "heynia.com" > dist/CNAME
            echo "Created CNAME with content:"
            cat dist/CNAME
          fi
          
          # List all files in dist to verify
          echo "Files in dist directory:"
          ls -la dist/
          
          # Ensure permissions are correct
          chmod -R 755 dist
          echo "✅ Permissions set"
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      
      - name: Verify Deployment
        run: |
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"
          echo "If your site is still not available at heynia.com, please check:"
          echo "1. GitHub repository settings -> Pages -> Custom domain is set to heynia.com"
          echo "2. DNS records are correctly configured in your domain provider"
          echo "3. Wait for DNS propagation (can take up to 24-48 hours)"
